CREATE TYPE subscription_status AS ENUM ('active', 'paused', 'cancelled');
CREATE TYPE payment_status AS ENUM ('pending', 'success', 'failed');
CREATE TYPE failure_policy AS ENUM ('pause', 'retry', 'skip');
CREATE TYPE contract_status AS ENUM ('proposed', 'active', 'rejected', 'superseded');

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payer_wallet_id INTEGER NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,
    payee_wallet_id INTEGER NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,

    current_contract_id BIGINT NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
    next_run_at TIMESTAMPTZ,
    start_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    status subscription_status NOT NULL DEFAULT 'active',
    runs_count INTEGER NOT NULL DEFAULT 0,
    failure_policy failure_policy DEFAULT 'pause',
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- contract offers (created by payees; payers may subscribe)
CREATE TABLE contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payee_wallet_id INTEGER NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,

    amount NUMERIC(16,2) NOT NULL CHECK (amount > 0),

    cron_expr TEXT NOT NULL,

    status subscription_status NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE offer_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL REFERENCES contract_offers(id) ON DELETE CASCADE,
    proposer_wallet_id INTEGER NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,

    proposed_amount NUMERIC(16,2) NOT NULL CHECK (proposed_amount > 0),
    proposed_cron_expr TEXT NOT NULL,

    payer_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    payer_accepted_at TIMESTAMPTZ,

    status contract_status NOT NULL DEFAULT 'proposed',
    applied_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- add the FK to avoid circular DDL ordering in migrations:
ALTER TABLE subscriptions ADD COLUMN offer_id BIGINT REFERENCES contract_offers(id) ON DELETE SET NULL;

CREATE INDEX idx_contracts_subscription_id ON subscription_contracts (subscription_id);
CREATE INDEX idx_subscriptions_next_run_active ON subscriptions (next_run_at) WHERE status = 'active';
